name: Run Hello Script

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run hello.sh
        run: |
          chmod +x hello.sh
          ./hello.sh
